version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - Nikos410
  ignore:
  - dependency-name: github.com/zmb3/spotify
    versions:
    - 1.1.1
  - dependency-name: gorm.io/gorm
    versions:
    - 1.20.12
    - 1.21.1
  - dependency-name: github.com/getsentry/sentry-go
    versions:
    - 0.10.0
    - 0.9.0
  - dependency-name: gorm.io/driver/postgres
    versions:
    - 1.0.7
    - 1.0.8
  - dependency-name: github.com/golang-migrate/migrate/v4
    versions:
    - 4.14.1
