spotifete:
  baseUrl: http://localhost:8410
  port: 8410
  releaseMode: true
  logDirectory: /var/log/spotifete
database:
  host: postgres.host.de
  port: 5432
  name: database-name
  user: database-user
  password: database-password
  disableSsl: false
spotify:
  id: client-id
  secret: client-secret
sentry:
  dsn: https://somedsn@sentry.io/someprojectid