spotifete:
  baseUrl: http://localhost:8410
  releaseMode: true
  app:
    androidUrl: https://github.com/47-11/SpotiFete-App/releases/latest
database:
  host: postgres.host.de
  port: 5432
  name: database-name
  user: database-user
  password: database-password
  disableSsl: false
spotify:
  id: client-id
  secret: client-secret
sentry:
  dsn: https://somedsn@sentry.io/someprojectid