server:
  activeProfile: debug
  baseUrl: http://spotifete.nikos410.de
database:
  host: postgres.host.de
  port: 5432
  name: database-name
  user: database-user
  password: database-password
spotify:
  id: client-id
  secret: client-secret
sentry:
  dsn: https://somedsn@sentry.io/someprojectid