name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number of the release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          
      - name: Merge develop into master
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: 'develop'
          target_branch: 'master'
          commit_message_template: '[Release] Merge develop into master'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nikos410/spotifete:${{ github.event.inputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
