name: Release

on:
  push:
    branches:
      - ci-testing

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout master
        run: | 
          git clone https://github.com/partyoffice/spotifete.git ./
          git checkout -f master

      - name: Evaluate version
        run: |
          VERSION=`git describe --tags | sed -r 's/v?([^-]*)-.*/\1/`
          IFS='.'; VERSION_PARTS=($VERSION); unset IFS
          VERSION_MAJOR=${VERSION_PARTS[0]}
          VERSION_MINOR=${VERSION_PARTS[1]}
          VERSION_PATCH=${VERSION_PARTS[2]}
          echo Major: $VERSION_MAJOR
          echo Minor: $VERSION_MINOR
          echo Patch: $VERSION_PATCH
