name: Release

on:
  push:
    branches:
      - ci-testing

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout master
        run: | 
          git clone https://github.com/partyoffice/spotifete.git ./
          git checkout -f master

      - name: Evaluate version
        run: |
          VERSION_TAG=$(git describe --tags)
          VERSION_MAJOR=$(echo $VERSION_TAG | sed -r 's/[^0-9]*([0-9]+)[.]([0-9]+)[.]([0-9])+.*/\1/')
          VERSION_MINOR=$(echo $VERSION_TAG | sed -r 's/[^0-9]*([0-9]+)[.]([0-9]+)[.]([0-9])+.*/\2/')
          VERSION_PATCH=$(echo $VERSION_TAG | sed -r 's/[^0-9]*([0-9]+)[.]([0-9]+)[.]([0-9])+.*/\3/')
          echo Major: $VERSION_MAJOR
          echo Minor: $VERSION_MINOR
          echo Patch: $VERSION_PATCH
