name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number of the release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nikos410/spotifete:${{ github.event.inputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
