name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check formatting
        run: go fmt ./... && git diff --exit-code

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build using docker
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
